import 'package:staredu/models/course_history_model.dart';

List<CourseHistoryModel> historyCourses = [
  CourseHistoryModel(
    id: 1,
    title: "Matematika",
    order: "Tanggal Order : 15 JAnuari 2023",
    img: "assets/images/calculator.jpg",
    kursus: "Matematika",
    kategori: "SMA/SMK Kelas 12",
    nama: "Ericha Septiana",
    telepon: "+62 859 4301 1086",
    email: "erichasr10@gmail.com",
    negara: "Indonesia",
    harga: "Rp. 750.000,00",
    pembayaran: "Transfer Bank",
    tanggal: "Januari 15, 2023 | 10:30:15 AM",
    idTransaksi: "TFB85943011086",
    status: "Sukses",
  ),
  CourseHistoryModel(
    id: 2,
    title: "Bahasa Inggris",
    order: "Tanggal Order : 25 Februari 2023",
    img: "assets/images/calculator.jpg",
    kursus: "Bahasa Inggris",
    kategori: "SMA/SMK Kelas 12",
    nama: "Ericha Septiana",
    telepon: "+62 859 4301 1086",
    email: "erichasr10@gmail.com",
    negara: "Indonesia",
    harga: "Rp. 750.000,00",
    pembayaran: "Transfer Bank",
    tanggal: "Januari 15, 2023 | 10:30:15 AM",
    idTransaksi: "TFB85943011086",
    status: "Sukses",
  ),
  CourseHistoryModel(
    id: 3,
    title: "Geografi",
    order: "Tanggal Order : 30 Maret 2023",
    img: "assets/images/calculator.jpg",
  ),
  CourseHistoryModel(
    id: 4,
    title: "Ekonomi",
    order: "Tanggal Order : 05 April 2023",
    img: "assets/images/calculator.jpg",
  ),
  CourseHistoryModel(
    id: 5,
    title: "Sejarah Indonesia",
    order: "Tanggal Order : 01 Mei 2023",
    img: "assets/images/calculator.jpg",
  ),
];
