import 'package:staredu/models/course_taken_model_dummy.dart';

List<CourseTakenModelDummy> courseTaken = [
  CourseTakenModelDummy(
      id: "1",
      img: "assets/images/calculator.jpg",
      title: "Matematika Dasar",
      currentSection: "9",
      totalSection: "11",
      progress: 80,
      score: "0",
      certificateStatus: false),
  CourseTakenModelDummy(
      id: "2",
      img: "assets/images/idea.jpg",
      title: "Fisika",
      currentSection: "9",
      totalSection: "11",
      progress: 100,
      score: "95",
      certificateStatus: true),
  CourseTakenModelDummy(
      id: "3",
      img: "assets/images/pencil.jpg",
      title: "Sejarah Indonesia",
      currentSection: "9",
      totalSection: "11",
      progress: 100,
      score: "100",
      certificateStatus: true),
  CourseTakenModelDummy(
      id: "3",
      img: "assets/images/pencil.jpg",
      title: "Sejarah Indonesia",
      currentSection: "9",
      totalSection: "11",
      progress: 30,
      score: "0",
      certificateStatus: false),
  CourseTakenModelDummy(
      id: "1",
      img: "assets/images/notebook.jpg",
      title: "Komputasi Dasar",
      currentSection: "9",
      totalSection: "11",
      progress: 50,
      score: "0",
      certificateStatus: false),
  CourseTakenModelDummy(
      id: "1",
      img: "assets/images/camera.jpg",
      title: "Videografi",
      currentSection: "9",
      totalSection: "11",
      progress: 0,
      score: "0",
      certificateStatus: false),
];
