import '../../models/module_list_model.dart';

final List<ModuleListModel> moduleList = [
  ModuleListModel(
      id: 1,
      courseId: 1,
      title: "Pengenalan courseId 1",
      video: true,
      material: false,
      assignment: true,
      quiz: false,
      finished: true),
  ModuleListModel(
    id: 2,
    courseId: 1,
    title: "List 2 courseId 1",
    video: true,
    material: true,
    assignment: true,
    quiz: true,
    finished: true,
  ),
  ModuleListModel(
    id: 3,
    courseId: 1,
    title: "List 3 courseId 1",
    video: true,
    material: true,
    assignment: true,
    quiz: true,
    finished: false,
  ),
  ModuleListModel(
      id: 1,
      courseId: 2,
      title: "Pengenalan courseId 2",
      video: true,
      material: false,
      assignment: true,
      quiz: false,
      finished: true),
  ModuleListModel(
    id: 2,
    courseId: 2,
    title: "List 2 courseId 2",
    video: true,
    material: true,
    assignment: true,
    quiz: true,
    finished: true,
  ),
  ModuleListModel(
    id: 3,
    courseId: 2,
    title: "List 3 courseId 2",
    video: true,
    material: true,
    assignment: true,
    quiz: true,
    finished: false,
  ),
  ModuleListModel(
      id: 1,
      courseId: 3,
      title: "Pengenalan courseId 3",
      video: true,
      material: false,
      assignment: true,
      quiz: false,
      finished: true),
  ModuleListModel(
    id: 2,
    courseId: 3,
    title: "List 2 courseId 3",
    video: true,
    material: true,
    assignment: true,
    quiz: true,
    finished: true,
  ),
  ModuleListModel(
    id: 3,
    courseId: 3,
    title: "List 3 courseId 3",
    video: true,
    material: true,
    assignment: true,
    quiz: true,
    finished: false,
  ),
];
