// import '../../models/sell_course_model.dart';

// List<SellCourseModel> sellCourses = [
//   SellCourseModel(
//       id: 1,
//       title: "Matematika",
//       price: "Rp. 750.000",
//       rating: "4.8",
//       student: "8950 Siswa",
//       img: "assets/images/calculator.png",
//       grade: "Kelas 12"),
//   SellCourseModel(
//       id: 2,
//       title: "Bahasa Inggris",
//       price: "Rp. 499.000",
//       rating: "4.8",
//       student: "8950 Siswa",
//       img: "assets/images/calculator.png",
//       grade: "Kelas 11"),
//   SellCourseModel(
//       id: 3,
//       title: "Geografi",
//       price: "Rp. 399.000",
//       rating: "4.8",
//       student: "8950 Siswa",
//       img: "assets/images/calculator.png",
//       grade: "Kelas 10"),
//   SellCourseModel(
//       id: 4,
//       title: "Sejarah Indonesia Merdeka",
//       price: "Rp. 550.000",
//       rating: "4.8",
//       student: "8950 Siswa",
//       img: "assets/images/calculator.png",
//       grade: "Kelas 12"),
// ];

final sellCoursesResponse = [
  {
    "ID": 58,
    "CreatedAt": "2023-06-20T15:57:10.514Z",
    "UpdatedAt": "2023-06-20T15:57:10.514Z",
    "DeletedAt": null,
    "category_id": null,
    "category": {"category_name": ""},
    "class_id": null,
    "class": {"class_name": "10 SMK"},
    "mentor_id": 13,
    "user": {
      "name": "",
      "email": "",
      "password": "",
      "role": "",
      "phone_number": "",
      "status": "",
      "school_name": "",
      "class": "",
      "gender": "",
      "profile": ""
    },
    "major_id": null,
    "major": {"major_name": "RPL"},
    "course_name": "Fisika",
    "price": "780000",
    "duration": "",
    "status": "draft",
    "description": "",
    "thumbnail": "notebook",
    "live_session_week": "rabu 21/06/2023",
    "num_students": 0,
    "scores": 5.0,
    "section_count": 4
  },
  {
    "ID": 59,
    "CreatedAt": "2023-06-20T15:57:10.514Z",
    "UpdatedAt": "2023-06-20T15:57:10.514Z",
    "DeletedAt": null,
    "category_id": null,
    "category": {"category_name": ""},
    "class_id": null,
    "class": {"class_name": "10"},
    "mentor_id": 13,
    "user": {
      "name": "",
      "email": "",
      "password": "",
      "role": "",
      "phone_number": "",
      "status": "",
      "school_name": "",
      "class": "",
      "gender": "",
      "profile": ""
    },
    "major_id": null,
    "major": {"major_name": "Umum"},
    "course_name": "Aljabar",
    "price": "870000",
    "duration": "",
    "status": "publish",
    "description": "",
    "thumbnail": "apple",
    "live_session_week": "sabtu 21/06/2023",
    "num_students": 2424,
    "scores": 4.8,
    "section_count": 4
  }
];
